name: Deploy to Server without SSH key

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Vérifie le dépôt
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Déploie le code sur le serveur (avec authentification par mot de passe)
      - name: Deploy code to server using password
        run: |
          expect <<EOF
          spawn ssh -o StrictHostKeyChecking=no adminuser@152.228.214.11
          expect "password:"
          send "YOUR_PASSWORD_HERE\r"
          expect "$ "
          send "cd /var/www/pelerinage && git pull origin main && npm install && pm2 restart all\r"
          expect "$ "
          send "exit\r"
          expect eof
          EOF
