name: Deploy to Server

on:
  push:
    branches:
      - main  # Déclencher l'action lorsqu'un push est effectué sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy code to server
        run: |
          ssh -o StrictHostKeyChecking=no adminuser@152.228.214.11 "
            cd /var/www/pelerinage &&
            git pull origin main &&
            npm install &&
            pm2 restart all
          "
